language: java

jdk:
  - openjdk12

install: mvn -pl backend install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - stage: Unit Tests
      script: mvn -pl backend test -B -V

    - stage: Integration Tests
      install: skip
      before_script:
        - psql -c 'create database "mymedialib-test";' -U postgres
        - mvn -pl backend flyway:baseline flyway:migrate -Dflyway.url=jdbc:postgresql://localhost/mymedialib-test -Dflyway.user=postgres -Dflyway.password=
      script: mvn -pl backend install -DskipTests

    - stage: Release
      install:
       - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: skip

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11