language: java

jdk:
  - openjdk12

install: mvn -pl backend install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: mvn -pl backend test -B -V

    - name: "Integration Tests"
      before_install:
        - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
        - sudo apt-get update
        - sudo apt-get --yes remove postgresql\*
        - sudo apt-get install -y postgresql-11 postgresql-client-11
        - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
        - sudo service postgresql restart 11
        - cp ci-config/travis-ci.application.yml backend/src/test/resources/application.yml
      install: skip
      before_script:
        - psql -c 'create database "mymedialib-test";' -U postgres
        - mvn -pl backend flyway:baseline flyway:migrate -Dflyway.url=jdbc:postgresql://localhost/mymedialib-test -Dflyway.user=postgres -Dflyway.password= -B -V
      script: mvn -pl backend test -Pintegration-tests -Dtmdb.api.key=$TMDB_API_KEY -B -V

    - name: "Sonar analysis"
      script: mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=valychbreak_MyMediaLib -Dsonar.login=${SONAR_TOKEN}
      #   - mvn -pl backend clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=valychbreak_MyMediaLib

    - stage: Release
      install:
       - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: skip

addons:
  postgresql: "11"
  sonarcloud:
    organization: "valychbreak"
    token:
      secure: $SONAR_TOKEN
