language: java

jdk:
  - openjdk12

install: mvn -pl backend install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - stage: test
      script: mvn -pl backend package -DskipTests
    - # stage: test -- not required
      script: mvn -pl backend install -DskipTests
