version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    volumes:
      - /Users/valych/Documents/Development/MyMediaLib/backend/postgres_remove_tmp:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 1111:5432

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 3333:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin

  mymedialib:
    image: mymedialib
    depends_on:
      - postgres
    ports:
      - 8080:8080
    command: ["host.docker.internal", "1111"]
