spring:
  datasource:
    url: jdbc:postgresql://localhost:1111/mymedialib-test-flyway2
    username: dbuser
    password: dbtest
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


local:
  client:
    clientId: gigy
    clientSecret: secret
    accessTokenUri: http://localhost:8080/oauth/access_token
    userAuthorizationUri: http://localhost:8080/oauth/authorize
  resource:
    userInfoUri: http://localhost:8080/user

logging:
  level:
    org.springframework.security: DEBUG